struct DTGetTime
{	unsigned short status;
	plcdt DT1;
	plcbit enable;
};
_BUR_PUBLIC void DTGetTime(struct DTGetTime* inst);
struct TON
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON(struct TON* inst);
struct fbLascoZdxx
{	float IN;
	float MEM;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoZdxx(struct fbLascoZdxx* inst);
struct fbLascoBmin
{	unsigned char(* Minuten);
	unsigned char Sekunden;
	plcbit Aktiv;
	plcbit sekTick;
	plcbit Reset;
};
_BUR_PUBLIC void fbLascoBmin(struct fbLascoBmin* inst);
struct fbLascoStdMin
{	unsigned char(* Minuten);
	unsigned long(* Stunden);
	plcbit Reset;
};
_BUR_PUBLIC void fbLascoStdMin(struct fbLascoStdMin* inst);
struct fbLascoSrvcInterv
{	unsigned long SrvcIntervall;
	unsigned long(* ZeitBisSrvc);
	plcbit Aktiv;
	plcbit Tick;
	plcbit SrvcReset;
	plcbit SrvcErforderl;
	plcbit zzEdge00000;
};
_BUR_PUBLIC void fbLascoSrvcInterv(struct fbLascoSrvcInterv* inst);
struct fbRestzeit
{	unsigned char AktuelleStunde;
	unsigned char AktuelleMinute;
	plcbit(* ZeitfensterIn)[24];
	unsigned short RestzeitStundenOut;
	unsigned short RestzeitMinutenOut;
	unsigned short loc_MinutenRestTag;
	signed long loc_Aenderung;
	unsigned char i;
	unsigned char loc_StundeEndeZeitfTag;
	unsigned short loc_MinutenRestFolgetag;
	unsigned char ii;
	unsigned char loc_StundeEndeZeitfFolgetag;
	unsigned short loc_MinutenRestGesamt;
	unsigned short loc_RestzeitStunden;
	plcbit Freigabe;
	plcbit ZeitfensterAktiv;
	plcbit MEM_ZeitfensterIn;
	plcbit loc_firstInitLauf;
	plcbit loc_firstInitPause;
};
_BUR_PUBLIC void fbRestzeit(struct fbRestzeit* inst);
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_0;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_1;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_2;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_3;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_4;
_BUR_LOCAL plcbit sekTick;
_BUR_LOCAL plcbit minTick;
_BUR_LOCAL plcbit tagTick;
_BUR_LOCAL plcbit monatTick;
_BUR_LOCAL plcbit jahrTick;
_BUR_LOCAL struct fbLascoBmin fbMinutenUmluftbetrGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenUmluftbetrGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenFrischluftbetrGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenFrischluftbetrGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenAbluftventGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenAbluftventGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentilator1Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentilator1Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentilator2Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentilator2Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenOelsumpfhGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenOelsumpfhGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenKompressor1Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenKompressor1Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenKompressor2Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenKompressor2Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenAbtauung1Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenAbtauung1Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenAbtauung2Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenAbtauung2Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenWarmluftofenGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenWarmluftofenGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenScheitholzofenGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenScheitholzofenGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenHeizregisterGes;
_BUR_LOCAL struct fbLascoStdMin fbStundenHeizregisterGes;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox1Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox1Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox2Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox2Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox3Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox3Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox4Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox4Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox5Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox5Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox6Ges;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox6Ges;
_BUR_LOCAL struct fbLascoBmin fbMinutenUmluftbetr;
_BUR_LOCAL struct fbLascoStdMin fbStundenUmluftbetr;
_BUR_LOCAL struct fbLascoBmin fbMinutenFrischluftbetr;
_BUR_LOCAL struct fbLascoStdMin fbStundenFrischluftbetr;
_BUR_LOCAL struct fbLascoBmin fbMinutenAbluftvent;
_BUR_LOCAL struct fbLascoStdMin fbStundenAbluftvent;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentilator1;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentilator1;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentilator2;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentilator2;
_BUR_LOCAL struct fbLascoBmin fbMinutenOelsumpfh;
_BUR_LOCAL struct fbLascoStdMin fbStundenOelsumpfh;
_BUR_LOCAL struct fbLascoBmin fbMinutenKompressor1;
_BUR_LOCAL struct fbLascoStdMin fbStundenKompressor1;
_BUR_LOCAL struct fbLascoBmin fbMinutenKompressor2;
_BUR_LOCAL struct fbLascoStdMin fbStundenKompressor2;
_BUR_LOCAL struct fbLascoBmin fbMinutenAbtauung1;
_BUR_LOCAL struct fbLascoStdMin fbStundenAbtauung1;
_BUR_LOCAL struct fbLascoBmin fbMinutenAbtauung2;
_BUR_LOCAL struct fbLascoStdMin fbStundenAbtauung2;
_BUR_LOCAL struct fbLascoBmin fbMinutenWarmluftofen;
_BUR_LOCAL struct fbLascoStdMin fbStundenWarmluftofen;
_BUR_LOCAL struct fbLascoBmin fbMinutenScheitholzofen;
_BUR_LOCAL struct fbLascoStdMin fbStundenScheitholzofen;
_BUR_LOCAL struct fbLascoBmin fbMinutenHeizregister;
_BUR_LOCAL struct fbLascoStdMin fbStundenHeizregister;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox1;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox1;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentBox1;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentBox1;
_BUR_LOCAL struct fbLascoBmin fbMinutenLuftaufbBox1;
_BUR_LOCAL struct fbLascoStdMin fbStundenLuftaufbBox1;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentBox2;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentBox2;
_BUR_LOCAL struct fbLascoBmin fbMinutenLuftaufbBox2;
_BUR_LOCAL struct fbLascoStdMin fbStundenLuftaufbBox2;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentBox3;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentBox3;
_BUR_LOCAL struct fbLascoBmin fbMinutenLuftaufbBox3;
_BUR_LOCAL struct fbLascoStdMin fbStundenLuftaufbBox3;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentBox4;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentBox4;
_BUR_LOCAL struct fbLascoBmin fbMinutenLuftaufbBox4;
_BUR_LOCAL struct fbLascoStdMin fbStundenLuftaufbBox4;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentBox5;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentBox5;
_BUR_LOCAL struct fbLascoBmin fbMinutenLuftaufbBox5;
_BUR_LOCAL struct fbLascoStdMin fbStundenLuftaufbBox5;
_BUR_LOCAL struct fbLascoBmin fbMinutenVentBox6;
_BUR_LOCAL struct fbLascoStdMin fbStundenVentBox6;
_BUR_LOCAL struct fbLascoBmin fbMinutenLuftaufbBox6;
_BUR_LOCAL struct fbLascoStdMin fbStundenLuftaufbBox6;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox2;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox2;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox3;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox3;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox4;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox4;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox5;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox5;
_BUR_LOCAL struct fbLascoBmin fbMinutenBox6;
_BUR_LOCAL struct fbLascoStdMin fbStundenBox6;
_BUR_LOCAL struct fbLascoSrvcInterv fbSrvcUhrzeit;
_BUR_LOCAL struct DTGetTime DTGetTime_0;
_BUR_LOCAL unsigned long loc_UhrzeitAktuellUdint;
_BUR_LOCAL struct TON TON_MinLaufzeitOelsumpfh;
_BUR_LOCAL unsigned long loc_MinLaufzeitOelsumpf;
_BUR_LOCAL struct TON TON_ResetInit;
_BUR_LOCAL unsigned long loc_UhrzeitMEM_Udint;
_BUR_LOCAL plcbit initOk;
_BUR_LOCAL plcbit stateEntry;
_BUR_LOCAL unsigned long loc_ZeitStromausfall;
_BUR_LOCAL struct fbRestzeit fbRestzeitBox1;
_BUR_LOCAL struct fbRestzeit fbRestzeitBox2;
_BUR_LOCAL struct fbRestzeit fbRestzeitBox3;
_BUR_LOCAL struct fbRestzeit fbRestzeitBox4;
_BUR_LOCAL struct fbRestzeit fbRestzeitBox5;
_BUR_LOCAL struct fbRestzeit fbRestzeitBox6;
