#ifndef __AS__TYPE_CSV_DatObj1_typ
#define __AS__TYPE_CSV_DatObj1_typ
typedef struct CSV_DatObj1_typ
{	unsigned char Version[20];
	unsigned char Anlagename[20];
	unsigned char RPS_Device[20];
	unsigned char RPS_Zielpfad[20];
	unsigned char EXT_Device[20];
	unsigned char EXT_Zielpfad[20];
	unsigned char PC_IP_Adresse[20];
	unsigned char PC_Ordnerfreigabe[20];
	unsigned char PC_Username[20];
	unsigned char PC_Userpassword[20];
	unsigned char PC_Zielpfad[100];
} CSV_DatObj1_typ;
#endif

#ifndef __AS__TYPE_CSV_DatObj2_typ
#define __AS__TYPE_CSV_DatObj2_typ
typedef struct CSV_DatObj2_typ
{	signed long Tag_ID;
	unsigned char Tag_Variablenname[48];
	unsigned char Tag_Bezeichnung[60];
	unsigned char Tag_Einheit[32];
	unsigned char Tag_MIN[16];
	unsigned char Tag_MAX[16];
} CSV_DatObj2_typ;
#endif

struct FileCreate
{	unsigned long pDevice;
	unsigned long pFile;
	unsigned short status;
	unsigned long ident;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileCreate(struct FileCreate* inst);
struct FileOpen
{	unsigned long pDevice;
	unsigned long pFile;
	unsigned char mode;
	unsigned short status;
	unsigned long ident;
	unsigned long filelen;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileOpen(struct FileOpen* inst);
struct FileClose
{	unsigned long ident;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileClose(struct FileClose* inst);
struct FileRead
{	unsigned long ident;
	unsigned long offset;
	unsigned long pDest;
	unsigned long len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileRead(struct FileRead* inst);
struct FileWrite
{	unsigned long ident;
	unsigned long offset;
	unsigned long pSrc;
	unsigned long len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileWrite(struct FileWrite* inst);
struct FileCopy
{	unsigned long pSrcDev;
	unsigned long pSrc;
	unsigned long pDestDev;
	unsigned long pDest;
	unsigned char option;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileCopy(struct FileCopy* inst);
struct FileDelete
{	unsigned long pDevice;
	unsigned long pName;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void FileDelete(struct FileDelete* inst);
struct DirCreate
{	unsigned long pDevice;
	unsigned long pName;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DirCreate(struct DirCreate* inst);
struct DirRead
{	unsigned long pDevice;
	unsigned long pPath;
	unsigned long entry;
	unsigned char option;
	unsigned long pData;
	unsigned long data_len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DirRead(struct DirRead* inst);
struct DirInfo
{	unsigned long pDevice;
	unsigned long pPath;
	unsigned short status;
	unsigned long dirnum;
	unsigned long filenum;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DirInfo(struct DirInfo* inst);
struct DirCopy
{	unsigned long pSrcDev;
	unsigned long pSrcDir;
	unsigned long pDestDev;
	unsigned long pDestDir;
	unsigned char option;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DirCopy(struct DirCopy* inst);
struct DirDeleteEx
{	unsigned long pDevice;
	unsigned long pName;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DirDeleteEx(struct DirDeleteEx* inst);
struct DevMemInfo
{	unsigned long pDevice;
	unsigned short status;
	unsigned long freemem;
	unsigned long memsize;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DevMemInfo(struct DevMemInfo* inst);
struct DevLink
{	unsigned long pDevice;
	unsigned long pParam;
	unsigned short status;
	unsigned long handle;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void DevLink(struct DevLink* inst);
struct DatObjInfo
{	unsigned long pName;
	unsigned short status;
	unsigned long ident;
	unsigned long pDatObjMem;
	unsigned long len;
	unsigned char MemType;
	unsigned long Option;
	plcdt ChangeDate;
	plcbit enable;
};
_BUR_PUBLIC void DatObjInfo(struct DatObjInfo* inst);
_BUR_LOCAL unsigned char CR;
_BUR_LOCAL CSV_DatObj1_typ CSV_DatObj1;
_BUR_LOCAL CSV_DatObj2_typ CSV_DatObj2;
_BUR_LOCAL unsigned long data_len;
_BUR_LOCAL unsigned long data_len2;
_BUR_LOCAL unsigned long data_typ;
_BUR_LOCAL unsigned char Datei_Ende[2];
_BUR_LOCAL unsigned char Datensatz[60001];
_BUR_LOCAL unsigned long DatObj_Offset;
_BUR_LOCAL unsigned long DatObj1_Size;
_BUR_LOCAL unsigned long DatObj2_Size;
_BUR_LOCAL struct DatObjInfo DatObjInfo_01;
_BUR_LOCAL unsigned char DatObjInfo_01_Name[16];
_BUR_LOCAL struct DevLink DevLink_0;
_BUR_LOCAL struct DevMemInfo DevMemInfo_0;
_BUR_LOCAL unsigned short dimension;
_BUR_LOCAL struct DirCopy DirCopy_0;
_BUR_LOCAL struct DirCreate DirCreate_0;
_BUR_LOCAL struct DirDeleteEx DirDeleteEx_0;
_BUR_LOCAL struct DirInfo DirInfo_0;
_BUR_LOCAL struct DirRead DirRead_0;
_BUR_LOCAL plcdt DirRead_alt_Date;
_BUR_LOCAL unsigned long DirRead_alt_entry;
_BUR_LOCAL unsigned long DirRead_entry;
_BUR_LOCAL plcdt DirRead_neu_Date;
_BUR_LOCAL unsigned long DirRead_neu_entry;
_BUR_LOCAL unsigned long DirRead_Nr;
_BUR_LOCAL unsigned long ET;
_BUR_LOCAL struct FileClose FileClose_0;
_BUR_LOCAL struct FileCopy FileCopy_0;
_BUR_LOCAL struct FileCreate FileCreate_0;
_BUR_LOCAL struct FileDelete FileDelete_0;
_BUR_LOCAL unsigned long FileIdent;
_BUR_LOCAL unsigned long FileLength;
_BUR_LOCAL struct FileOpen FileOpen_0;
_BUR_LOCAL struct FileRead FileRead_0;
_BUR_LOCAL struct FileWrite FileWrite_0;
_BUR_LOCAL unsigned short i;
_BUR_LOCAL unsigned short ii;
_BUR_LOCAL signed char init_reason;
_BUR_LOCAL plcbit InitOK;
_BUR_LOCAL unsigned char LF;
_BUR_LOCAL plcbit M_date_Fehler;
_BUR_LOCAL plcdt M_DatObj_ChangDate;
_BUR_LOCAL plcbit M_Fehler;
_BUR_LOCAL plcbit M_File_neu;
_BUR_LOCAL plcbit M_InitOK;
_BUR_LOCAL plcbit M_MAX_Fehler;
_BUR_LOCAL plcbit M_MIN_Fehler;
_BUR_LOCAL plcbit M_Tag_ID[10000];
_BUR_LOCAL double M_Tag_MAX;
_BUR_LOCAL double M_Tag_MIN;
_BUR_LOCAL plcbit M_timestamp_Fehler;
_BUR_LOCAL plcbit M_timestamp_QM_Fehler;
_BUR_LOCAL plcbit M_UDINT_Fehler;
_BUR_LOCAL unsigned long nxt_adr;
_BUR_LOCAL unsigned long Offset_Ende;
_BUR_LOCAL plcbit(* P_Fehler);
_BUR_LOCAL plcbit(* P_Warnung);
_BUR_LOCAL unsigned long pv_adr;
_BUR_LOCAL unsigned short RT_Status;
_BUR_LOCAL unsigned short RTC_gettime_Status;
_BUR_LOCAL unsigned short status_adr;
_BUR_LOCAL unsigned short status_ninfo;
_BUR_LOCAL plcstring Str_date[11];
_BUR_LOCAL unsigned char Str_ID[12];
_BUR_LOCAL unsigned char Str_Min[12];
_BUR_LOCAL unsigned char Str_Nachkomma[12];
_BUR_LOCAL plcstring Str_QM_timestamp[15];
_BUR_LOCAL unsigned char Str_RPS_File_Name[301];
_BUR_LOCAL unsigned char Str_Sek[12];
_BUR_LOCAL unsigned char Str_Std[12];
_BUR_LOCAL unsigned char Str_Stellen[12];
_BUR_LOCAL plcstring Str_timestamp[24];
_BUR_LOCAL unsigned char Str_Ziel_File_Name[301];
_BUR_LOCAL unsigned char StrCRLF[4];
_BUR_LOCAL unsigned char StrWork[31];
_BUR_LOCAL unsigned char Tag_MAX_Komma;
_BUR_LOCAL unsigned char Tag_MAX_Nachkomma;
_BUR_LOCAL unsigned char Tag_MAX_Stellen;
_BUR_LOCAL unsigned char Tag_MIN_Komma;
_BUR_LOCAL unsigned char Tag_MIN_Nachkomma;
_BUR_LOCAL unsigned char Tag_MIN_Stellen;
_BUR_LOCAL unsigned char Tag_Nachkomma;
_BUR_LOCAL signed char task_class;
_BUR_LOCAL plcbit(* Wert_BOOL);
_BUR_LOCAL signed long Wert_DINT;
_BUR_LOCAL signed short Wert_INT;
_BUR_LOCAL float Wert_REAL;
_BUR_LOCAL signed char Wert_SINT;
_BUR_LOCAL unsigned char Wert_STRING[25];
_BUR_LOCAL unsigned long Wert_UDINT;
_BUR_LOCAL unsigned short Wert_UINT;
_BUR_LOCAL unsigned char Wert_USINT;
_BUR_LOCAL plcbit Zeile_Fertig;
_BUR_LOCAL unsigned long ZyklTime;
