#ifndef __AS__TYPE_
#define __AS__TYPE_
typedef struct {
	unsigned char bit0  : 1;
	unsigned char bit1  : 1;
	unsigned char bit2  : 1;
	unsigned char bit3  : 1;
	unsigned char bit4  : 1;
	unsigned char bit5  : 1;
	unsigned char bit6  : 1;
	unsigned char bit7  : 1;
} _1byte_bit_field_;

typedef struct {
	unsigned short bit0  : 1;
	unsigned short bit1  : 1;
	unsigned short bit2  : 1;
	unsigned short bit3  : 1;
	unsigned short bit4  : 1;
	unsigned short bit5  : 1;
	unsigned short bit6  : 1;
	unsigned short bit7  : 1;
	unsigned short bit8  : 1;
	unsigned short bit9  : 1;
	unsigned short bit10 : 1;
	unsigned short bit11 : 1;
	unsigned short bit12 : 1;
	unsigned short bit13 : 1;
	unsigned short bit14 : 1;
	unsigned short bit15 : 1;
} _2byte_bit_field_;

typedef struct {
	unsigned long bit0  : 1;
	unsigned long bit1  : 1;
	unsigned long bit2  : 1;
	unsigned long bit3  : 1;
	unsigned long bit4  : 1;
	unsigned long bit5  : 1;
	unsigned long bit6  : 1;
	unsigned long bit7  : 1;
	unsigned long bit8  : 1;
	unsigned long bit9  : 1;
	unsigned long bit10 : 1;
	unsigned long bit11 : 1;
	unsigned long bit12 : 1;
	unsigned long bit13 : 1;
	unsigned long bit14 : 1;
	unsigned long bit15 : 1;
	unsigned long bit16 : 1;
	unsigned long bit17 : 1;
	unsigned long bit18 : 1;
	unsigned long bit19 : 1;
	unsigned long bit20 : 1;
	unsigned long bit21 : 1;
	unsigned long bit22 : 1;
	unsigned long bit23 : 1;
	unsigned long bit24 : 1;
	unsigned long bit25 : 1;
	unsigned long bit26 : 1;
	unsigned long bit27 : 1;
	unsigned long bit28 : 1;
	unsigned long bit29 : 1;
	unsigned long bit30 : 1;
	unsigned long bit31 : 1;
} _4byte_bit_field_;
#endif

#ifndef __AS__TYPE_lcrpid_internal_typ
#define __AS__TYPE_lcrpid_internal_typ
typedef struct lcrpid_internal_typ
{	unsigned short size;
	plcbit valid;
	float WX_max;
	float WX_min;
	plcbit invert;
	float deadband;
	unsigned char deadband_mode;
	float dY_max;
	float Kp;
	float Kp_Tn;
	float Tv_Tf;
	float Tf_reciproc;
	float Kw;
	float Kfbk_Kp;
	float Kfbk_Kp_max;
	unsigned char fbk_mode;
	unsigned char d_mode;
	unsigned char force_mode;
	float Y_force;
	float W;
	float X;
	unsigned char pid_init;
	signed long Yp1;
	signed long Yp2;
	signed long dYi1;
	signed long dYi2;
	signed long Yi1;
	signed long Yi2;
	float dt_Tf;
	signed long a11;
	signed long a12;
	signed long a21;
	signed long a22;
	signed long Yd1;
	signed long Yd2;
	signed long Ytotal1;
	signed long Ytotal2;
	signed long Ylim1;
	signed long Ylim2;
	signed long Y1;
	signed long Y2;
	float deltaY_fbk;
	float e_fbk;
} lcrpid_internal_typ;
#endif

struct TON
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON(struct TON* inst);
struct LCRPIDpara
{	float WX_max;
	float WX_min;
	float deadband;
	unsigned char deadband_mode;
	float dY_max;
	float Kp;
	float Tn;
	float Tv;
	float Tf;
	float Kw;
	float Kfbk;
	unsigned char fbk_mode;
	unsigned char d_mode;
	unsigned short status;
	unsigned long ident;
	lcrpid_internal_typ internal_data;
	plcbit enable;
	plcbit enter;
	plcbit invert;
};
_BUR_PUBLIC void LCRPIDpara(struct LCRPIDpara* inst);
struct SysInfo
{	unsigned char init_reason;
	unsigned char init_count;
	unsigned long tick_count;
	unsigned long version;
	plcbit enable;
};
_BUR_PUBLIC void SysInfo(struct SysInfo* inst);
struct LCRScal
{	float x;
	float x1;
	float y1;
	float x2;
	float y2;
	float y;
};
_BUR_PUBLIC void LCRScal(struct LCRScal* inst);
struct LCRPID
{	unsigned long ident;
	float W;
	float X;
	float Y_max;
	float Y_min;
	float A;
	float Y_man;
	float Y_fbk;
	unsigned char mode;
	unsigned short status;
	float e;
	float Y;
	float Yp;
	float Yi;
	float Yd;
	float Yi_set;
	float Yi_min;
	float Yi_max;
	float Yi_minInternal;
	float Yi_maxInternal;
	float Tv_Tf_old;
	float e_old;
	unsigned short deadband_state;
	struct SysInfo sysinfo_inst;
	struct LCRScal scal_inst;
	unsigned long store1;
	unsigned long store2;
	unsigned long timeCnt;
	unsigned short musecs_old;
	plcbit enable;
	plcbit hold_I;
	plcbit Set_Yi;
	plcbit force_Yi;
	plcbit joltFreeDoneLowerLim;
	plcbit joltFreeDoneUpperLim;
	plcbit enable_old;
};
_BUR_PUBLIC void LCRPID(struct LCRPID* inst);
struct LCRLimScal
{	float x;
	float x1;
	float y1;
	float x2;
	float y2;
	float y;
};
_BUR_PUBLIC void LCRLimScal(struct LCRLimScal* inst);
struct fbRegPidReglerAllg
{	float Hysterese;
	float RampeMax;
	float WindupDaempfung;
	float P_Anteil;
	float AbschwaechungSollwert;
	float D_Filterzeit;
	float I_Anteil;
	float D_Anteil;
	float Aufschaltgroesse;
	unsigned char Mode;
	float Sollwert;
	float Istwert;
	float StellgroesseManuell;
	float StellgroesseMin;
	float StellgroesseMax;
	float RegelbereichMin;
	unsigned long Fehlerverzoegerung;
	float RegelbereichMax;
	float Stellgroesse;
	float Regelabweichung;
	struct LCRPIDpara PID_Para;
	struct LCRPID PID;
	struct TON TON_FehlerverzoegerungMin;
	struct TON TON_FehlerverzoegerungMax;
	struct LCRLimScal LCRLimScal_0;
	plcbit Freigabe;
	plcbit Invert;
	plcbit Hold_I;
	plcbit QuitFehler;
	plcbit FehlerRegelbereichMin;
	plcbit FehlerRegelbereichMax;
	plcbit WarnungRegelbereichMin;
	plcbit WarnungRegelbereichMax;
};
_BUR_PUBLIC void fbRegPidReglerAllg(struct fbRegPidReglerAllg* inst);
