/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20260617135235_
#define _LIBRARIES_20260617135235_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoMath/LascoMath.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoMath/LascoMath.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoMath/LascoMath.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoReg/LascoReg.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoReg/LascoReg.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoReg/LascoReg.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoTrock/LascoTrock.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoTrock/LascoTrock.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoTrock/LascoTrock.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoUtil/LascoUtil.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoUtil/LascoUtil.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoUtil/LascoUtil.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LaEntfV2/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LaEntfV2/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LaEntfV2/LaEntfV2.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoBoxen/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoBoxen/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LascoBoxen/LascoBoxen.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asstring/asstring.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsARCfg/AsARCfg.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/visapi/Visapi.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/visapi/Visapi.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/visapi/Visapi.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/dvframe/dvframe.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/dvframe/dvframe.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/dvframe/dvframe.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/IecCheck/IecCheck.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsTCP/AsTCP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CControl/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CControl/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/CControl/CControl.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpBase/MpBase.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpBase/MpBase.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpBase/MpBase.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFile.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFileError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFileAlarm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpFile/MpFile.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipe.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipeAlarm.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipeError.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/MpRecipe/MpRecipe.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/CSV/Library/CSV/CSV.fun\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii \"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADRINST\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RealTan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAtan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAsin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAcos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLog\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExpt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAbs\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealCos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSqrt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC3\\\" FUB\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii \"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii \"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_setval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"slMoList\\\" FUB\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatod\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _LASCOMATH_EXPORT
	__asm__(".ascii \"plcexport \\\"fbMathLuft\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbMathTrGutGew\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbMathTrLftMenge\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbMathTrLftDruck\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbMathWetter\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbMathMessblende\\\" FUB\\n\"");
#endif
#ifdef _LASCOREG_EXPORT
	__asm__(".ascii \"plcexport \\\"fbRegPidReglerAllg\\\" FUB\\n\"");
#endif
#ifdef _LASCOTROCK_EXPORT
	__asm__(".ascii \"plcexport \\\"fbTrockZeitprogramm\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockLaufPause\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockNachtrock\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockTarifabsch\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockStrombegr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockAutomatik\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockStufen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockVent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbTrockVariante\\\" FUB\\n\"");
#endif
#ifdef _LASCOUTIL_EXPORT
	__asm__(".ascii \"plcexport \\\"fbLascoAutoRuecklauf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoBskUeberw\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoEUhr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoTON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoTOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoTOG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"funLascoMinss\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoZdxx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoZbFrg\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoBstd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoBmin\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoStdMin\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoSrvcInterv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoBrStfLst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoWoPrg\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoDrzuebw\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoFehl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoFept\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoPuge\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoLstgStell\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoLstRamp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoZund\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoFU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoZweiPunktAchse\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoStellachse\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoStellachseAnalog\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoStellachseDigital\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoWarmluftsteller\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoFreilauf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoFuellst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoWlg\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoBsk\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoTrend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoTimerHand\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbLascoPugeV2\\\" FUB\\n\"");
#endif
#ifdef _LAENTFV2_EXPORT
	__asm__(".ascii \"plcexport \\\"fbEntfOelsumpfheiz\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbEntfKompressor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbEntfFremd\\\" FUB\\n\"");
#endif
#ifdef _LASCOBOXEN_EXPORT
	__asm__(".ascii \"plcexport \\\"fbBoxenKonfig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenVentKlappen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenKlappenanst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenAbluftkl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenAbluftvent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenUmschaltung\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenWLO\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenHeizreg\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenNotstrom\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenSHO\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbBoxenLuftmengen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"fbRestzeit\\\" FUB\\n\"");
#endif
#ifdef _LOOPCONR_EXPORT
	__asm__(".ascii \"plcexport \\\"LCRPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRScal\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRCurveByPoints\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPIDpara\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRContinServo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRRamp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRIntegrate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRLimit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRLimScal\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPWM\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRMovAvgFlt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTimeBasedOnOff\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRDifferentiate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRSlimPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPIDTune\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPFM\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRSimModExt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTt\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT1e\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRDblActPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRMinMax\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTempPID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRTempTune\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRPT2o\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LCRSchedulePWM\\\" FUB\\n\"");
#endif
#ifdef _BRSYSTEM_EXPORT
	__asm__(".ascii \"plcexport \\\"MEMInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MEMxInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RTInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TARGETInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"HWInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SysconfSet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"BatteryInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EXCInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ZYKVLenable\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemPut\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"PMemSize\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ARwinWindowsInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ARwinEthWinInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RTCyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTExit\\\" FUN\\n\"");
#endif
#ifdef _ASSTRING_EXPORT
	__asm__(".ascii \"plcexport \\\"ftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"itoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"memcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strcmp\\\" FUN\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii \"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _DATAOBJ_EXPORT
	__asm__(".ascii \"plcexport \\\"DatObjCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjMove\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjChangeDate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjAttach\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DatObjDetach\\\" FUB\\n\"");
#endif
#ifdef _ASARCFG_EXPORT
	__asm__(".ascii \"plcexport \\\"CfgGetInaNode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetInaNode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetIPAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetIPAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSubnetMask\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSubnetMask\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetClusterIPAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetClusterIPAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDefaultGateway\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDefaultGateway\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetBroadcastAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetBroadcastAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetEthBaudrate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetEthBaudrate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetEthConfigMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetEthConfigMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetHostName\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetHostName\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetHostNameIf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetHostNameIf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetMacAddr\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetFTPServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeOffset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetTimeOffset\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSntpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSntpClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSntpcData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSntpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetNtpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetNtpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetNtpClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetNtpcData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeZone\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetTimeZone\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeZoneInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetTimeZoneEntry\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDst\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetCIFSDomain\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetCIFSDomain\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetCIFSDefaultuser\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetCIFSDefaultuser\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDhcpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDhcpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDhcpsData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDhcpcOption\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgClearNV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmColor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmColor\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmCustomData1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmCustomData1\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetSdmCustomData2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetSdmCustomData2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebMimeType\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetWebMimeType\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerHttpsConfig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerPort\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerDevice\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebAspGoform\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetWebAspGoform\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetWebServerStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetWebServerStatus\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDnsMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDnsMode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDnsSuffix\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDnsSuffix\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgGetDnsAddress\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgSetDnsAddress\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgRouteAdd\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CfgRouteDelete\\\" FUB\\n\"");
#endif
#ifdef _VISAPI_EXPORT
	__asm__(".ascii \"plcexport \\\"VA_Attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_BlitBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Configure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_CopyScreenRect\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_DelAlarmHistory\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActiveAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Detach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_DrawBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Ellipse\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ExchangeFont\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ExtractKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_FreeBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetBrightness\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetDisplayInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetPanelStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetTouchAction\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_LangIsAvailable\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Line\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_LoadBitmap\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_NGetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Quit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_QuitAlarms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Rect\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Redraw\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Saccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SaveSettings\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBacklight\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBrightness\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetClipRegion\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetContrast\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetUserParam\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Setup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetupX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Shutdown\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Srelease\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartProject\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartVisuByName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartTouchCal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StopProject\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_Textout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_TimeSynchronize\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcAlarmGetList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcGetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_wcTextout\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetActualLang\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_ClearTouchEventBuffer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_RegisterClient\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_StartProcess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_TerminateProcess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_GetProcessExitCode\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetProcessZOrder\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetVisualizationZOrder\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_RunJScript\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"VA_SetBeep\\\" FUN\\n\"");
#endif
#ifdef _ASUSB_EXPORT
	__asm__(".ascii \"plcexport \\\"UsbNodeListGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UsbNodeGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UsbDescriptorGet\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UsbMsDeviceReady\\\" FUB\\n\"");
#endif
#ifdef _DVFRAME_EXPORT
	__asm__(".ascii \"plcexport \\\"FRM_mode\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_ctrl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_robuf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_gbuf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_rbuf\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_close\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_write\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_writeAcknowledged\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_read\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FRM_xopen\\\" FUB\\n\"");
#endif
#ifdef _IECCHECK_EXPORT
	__asm__(".ascii \"plcexport \\\"CheckDivSint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivUsint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivInt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivUint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivDint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivUdint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivReal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckDivLReal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckBounds\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckRange\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckSignedSubrange\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckUnsignedSubrange\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckReadAccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CheckWriteAccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MakeEntry\\\" FUN\\n\"");
#endif
#ifdef _ASTCP_EXPORT
	__asm__(".ascii \"plcexport \\\"TcpOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpOpenSsl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpServer\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpClient\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpSend\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpRecv\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TcpIoctl\\\" FUB\\n\"");
#endif
#ifdef _CCONTROL_EXPORT
	__asm__(".ascii \"plcexport \\\"fbCControlWitterung\\\" FUB\\n\"");
#endif
#ifdef _MPBASE_EXPORT
	__asm__(".ascii \"plcexport \\\"MpComHandle\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MpComVersion\\\" FUN\\n\"");
#endif
#ifdef _MPFILE_EXPORT
	__asm__(".ascii \"plcexport \\\"MpFileManagerUI\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MpFileManagerConfig\\\" FUB\\n\"");
#endif
#ifdef _MPRECIPE_EXPORT
	__asm__(".ascii \"plcexport \\\"MpRecipeRegParSync\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MpRecipeRegPar\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MpRecipeXml\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MpRecipeUI\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"MpRecipeCsv\\\" FUB\\n\"");
#endif
#ifdef _CSV_EXPORT
	__asm__(".ascii \"plcexport \\\"CSV_Tick\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_itoa\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_GRP_date\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_GRP_time\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_GRP_timestamp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_QM_timestamp\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_atoLREAL\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CSV_UDINTtoa\\\" FUB\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20260617135235_ */

