struct TON_10ms
{	unsigned long PT;
	unsigned long ET;
	unsigned long StartTime;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON_10ms(struct TON_10ms* inst);
struct fbLascoZdxx
{	float IN;
	float MEM;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoZdxx(struct fbLascoZdxx* inst);
struct CfgGetIPAddr
{	unsigned long pDevice;
	unsigned long pIPAddr;
	unsigned char Len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgGetIPAddr(struct CfgGetIPAddr* inst);
struct CfgSetIPAddr
{	unsigned long pDevice;
	unsigned long pIPAddr;
	unsigned long Option;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgSetIPAddr(struct CfgSetIPAddr* inst);
struct CfgGetSubnetMask
{	unsigned long pDevice;
	unsigned long pSubnetMask;
	unsigned char Len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgGetSubnetMask(struct CfgGetSubnetMask* inst);
struct CfgSetSubnetMask
{	unsigned long pDevice;
	unsigned long pSubnetMask;
	unsigned long Option;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgSetSubnetMask(struct CfgSetSubnetMask* inst);
struct CfgGetDefaultGateway
{	unsigned long pDevice;
	unsigned long pGateway;
	unsigned char Len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgGetDefaultGateway(struct CfgGetDefaultGateway* inst);
struct CfgSetDefaultGateway
{	unsigned long pDevice;
	unsigned long pGateway;
	unsigned long Option;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgSetDefaultGateway(struct CfgSetDefaultGateway* inst);
struct CfgGetHostName
{	unsigned long pHostName;
	unsigned char Len;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgGetHostName(struct CfgGetHostName* inst);
struct CfgSetHostName
{	unsigned long pHostName;
	unsigned long Option;
	unsigned short status;
	unsigned short i_state;
	unsigned short i_result;
	unsigned long i_tmp;
	plcbit enable;
};
_BUR_PUBLIC void CfgSetHostName(struct CfgSetHostName* inst);
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_0;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_1;
_BUR_LOCAL plcbit bildTick;
_BUR_LOCAL plcbit sekTick;
_BUR_LOCAL plcstring Device[17];
_BUR_LOCAL plcbit loc_GetEthernet;
_BUR_LOCAL struct TON_10ms TON_10ms_0;
_BUR_LOCAL unsigned short CfgSetIPAddr_status;
_BUR_LOCAL unsigned short CfgSetDefaultGateway_status;
_BUR_LOCAL unsigned short CfgSetSubnetMask_status;
_BUR_LOCAL unsigned short CfgSetHostName_status;
_BUR_LOCAL struct CfgSetIPAddr CfgSetIPAddr_0;
_BUR_LOCAL struct CfgSetSubnetMask CfgSetSubnetMask_0;
_BUR_LOCAL struct CfgSetDefaultGateway CfgSetDefaultGateway_0;
_BUR_LOCAL struct CfgSetHostName CfgSetHostName_0;
_BUR_LOCAL unsigned short CfgGetIPAddr_status;
_BUR_LOCAL unsigned short CfgGetSubnetMask_status;
_BUR_LOCAL unsigned short CfgGetDefaultGateway_status;
_BUR_LOCAL unsigned short CfgGetHostName_status;
_BUR_LOCAL struct CfgGetIPAddr CfgGetIPAddr_0;
_BUR_LOCAL struct CfgGetSubnetMask CfgGetSubnetMask_0;
_BUR_LOCAL struct CfgGetDefaultGateway CfgGetDefaultGateway_0;
_BUR_LOCAL struct CfgGetHostName CfgGetHostName_0;
