struct TOF
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TOF(struct TOF* inst);
struct fbLascoZdxx
{	float IN;
	float MEM;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoZdxx(struct fbLascoZdxx* inst);
struct fbLascoPuge
{	float ZeitPuls;
	float ZeitPause;
	float RestzeitPuls;
	float RestzeitPause;
	unsigned char currStep;
	float CounterPuls;
	float CounterPause;
	unsigned char nextStep;
	plcbit StartMitPuls;
	plcbit StartMitPause;
	plcbit Tick;
	plcbit Reset;
	plcbit PulsQ;
	plcbit PauseQ;
};
_BUR_PUBLIC void fbLascoPuge(struct fbLascoPuge* inst);
_BUR_LOCAL struct TOF TOF_VerzBetriebsartBox;
_BUR_LOCAL struct TOF TOF_BoxAufgerufen;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_0;
_BUR_LOCAL plcbit hmilliTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_1;
_BUR_LOCAL plcbit sekTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_2;
_BUR_LOCAL plcbit stdTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_3;
_BUR_LOCAL plcbit tagTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_5;
_BUR_LOCAL plcbit jahrTick;
_BUR_LOCAL struct fbLascoPuge fbLascoPuge_0;
_BUR_LOCAL plcbit hmiBlink;
_BUR_LOCAL struct fbLascoPuge fbLascoPuge_1;
_BUR_LOCAL plcbit hmiBlink2;
_BUR_LOCAL struct TOF TOF_VerzUmschaltungBypassklappe;
_BUR_LOCAL struct TOF TOF_VerzUmschaltungAbluftklappe;
_BUR_LOCAL struct TOF TOF_VerzUmschaltungAbluftvent;
_BUR_LOCAL struct TOF TOF_VerzUmschaltungUmluftkl;
_BUR_LOCAL unsigned long loc_TimePwReset;
_BUR_LOCAL plcbit loc_MsgFalschesDatumAckn;
_BUR_LOCAL plcbit loc_MsgKontrUhrzeitAckn;
_BUR_LOCAL signed short loc_DisplayTimeout;
_BUR_LOCAL float loc_RestzeitSchlechtMillisek;
_BUR_LOCAL unsigned long loc_RestzeitSchlechtStunden;
_BUR_LOCAL unsigned short loc_RestzeitSchlechtMinuten;
