#ifndef __AS__TYPE_
#define __AS__TYPE_
typedef struct {
	unsigned char bit0  : 1;
	unsigned char bit1  : 1;
	unsigned char bit2  : 1;
	unsigned char bit3  : 1;
	unsigned char bit4  : 1;
	unsigned char bit5  : 1;
	unsigned char bit6  : 1;
	unsigned char bit7  : 1;
} _1byte_bit_field_;

typedef struct {
	unsigned short bit0  : 1;
	unsigned short bit1  : 1;
	unsigned short bit2  : 1;
	unsigned short bit3  : 1;
	unsigned short bit4  : 1;
	unsigned short bit5  : 1;
	unsigned short bit6  : 1;
	unsigned short bit7  : 1;
	unsigned short bit8  : 1;
	unsigned short bit9  : 1;
	unsigned short bit10 : 1;
	unsigned short bit11 : 1;
	unsigned short bit12 : 1;
	unsigned short bit13 : 1;
	unsigned short bit14 : 1;
	unsigned short bit15 : 1;
} _2byte_bit_field_;

typedef struct {
	unsigned long bit0  : 1;
	unsigned long bit1  : 1;
	unsigned long bit2  : 1;
	unsigned long bit3  : 1;
	unsigned long bit4  : 1;
	unsigned long bit5  : 1;
	unsigned long bit6  : 1;
	unsigned long bit7  : 1;
	unsigned long bit8  : 1;
	unsigned long bit9  : 1;
	unsigned long bit10 : 1;
	unsigned long bit11 : 1;
	unsigned long bit12 : 1;
	unsigned long bit13 : 1;
	unsigned long bit14 : 1;
	unsigned long bit15 : 1;
	unsigned long bit16 : 1;
	unsigned long bit17 : 1;
	unsigned long bit18 : 1;
	unsigned long bit19 : 1;
	unsigned long bit20 : 1;
	unsigned long bit21 : 1;
	unsigned long bit22 : 1;
	unsigned long bit23 : 1;
	unsigned long bit24 : 1;
	unsigned long bit25 : 1;
	unsigned long bit26 : 1;
	unsigned long bit27 : 1;
	unsigned long bit28 : 1;
	unsigned long bit29 : 1;
	unsigned long bit30 : 1;
	unsigned long bit31 : 1;
} _4byte_bit_field_;
#endif

#ifndef __AS__TYPE_Zeit_type
#define __AS__TYPE_Zeit_type
typedef struct Zeit_type
{	unsigned short Jahr;
	unsigned char Monat;
	unsigned char Tag;
	unsigned char WoTag;
	unsigned char Stunde;
	unsigned char Minute;
	unsigned char Sekunde;
	unsigned short Milli;
	unsigned short Mikro;
} Zeit_type;
#endif

struct DTGetTime
{	unsigned short status;
	plcdt DT1;
	plcbit enable;
};
_BUR_PUBLIC void DTGetTime(struct DTGetTime* inst);
struct TON
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON(struct TON* inst);
struct fbLascoEUhr
{	signed short StdMin;
	unsigned short Jahr;
	unsigned char Monat;
	unsigned char Tag;
	unsigned char WoTag;
	unsigned char Stunde;
	unsigned char Minute;
	unsigned char Sekunde;
	unsigned short Milli;
	unsigned short Mikro;
	Zeit_type Echtzeit;
	struct DTGetTime DTGetTime_0;
	plcdt DateTime;
	plcbit Freigabe;
};
_BUR_PUBLIC void fbLascoEUhr(struct fbLascoEUhr* inst);
struct fbLascoTON
{	float Zeit;
	float Elapsed;
	plcbit IN;
	plcbit Tick;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoTON(struct fbLascoTON* inst);
struct fbLascoZdxx
{	float IN;
	float MEM;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoZdxx(struct fbLascoZdxx* inst);
struct SysInfo
{	unsigned char init_reason;
	unsigned char init_count;
	unsigned long tick_count;
	unsigned long version;
	plcbit enable;
};
_BUR_PUBLIC void SysInfo(struct SysInfo* inst);
struct LCRRamp
{	float x;
	float dy_up;
	float dy_down;
	float y_max;
	float y_min;
	float y_set;
	unsigned short status;
	float y;
	signed long y_dbl_1;
	signed long y_dbl_2;
	unsigned long timestore1;
	unsigned long timestore2;
	unsigned long getDtForceOff;
	struct SysInfo sysinfo_inst;
	plcbit enable;
	plcbit set;
	plcbit x_reached;
	plcbit max_limit;
	plcbit min_limit;
};
_BUR_PUBLIC void LCRRamp(struct LCRRamp* inst);
struct fbLascoFU
{	float SollDrehzahl;
	float AnsprechZeitFU;
	float RampeUpSek;
	float RampeDownSek;
	float MaxDrehzahl;
	float MinDrehzahl;
	float DrehzahlFU;
	struct fbLascoTON TON_Betriebsmeldung;
	struct LCRRamp LCRRamp_0;
	signed long RampDownMillis;
	signed long RampUpMillis;
	float IstDrehzahl;
	plcbit Freigabe;
	plcbit BetrMldg;
	plcbit Reset;
	plcbit Tick;
	plcbit BetriebFU;
	plcbit StoerungFU;
	plcbit zzEdge00000;
	plcbit zzEdge00001;
	plcbit zzEdge00002;
	plcbit InitDone;
	plcbit ResetDone;
	plcbit Init;
	plcbit zzEdge00003;
};
_BUR_PUBLIC void fbLascoFU(struct fbLascoFU* inst);
struct fbBoxenKlappenanst
{	unsigned long LaufzeitOeffnen;
	unsigned long LaufzeitSchliessen;
	unsigned char step;
	struct TON TON_Laufzeit;
	struct TON TON_AnzVerz;
	plcbit Stoerung;
	plcbit QuitFehler;
	plcbit Oeffnen;
	plcbit Schliessen;
	plcbit EndlageOffen;
	plcbit EndlageGeschl;
	plcbit EndlagenVhd;
	plcbit OeffnenOut;
	plcbit SchliessenOut;
	plcbit FehlerLaufzeitOeffnen;
	plcbit FehlerLaufzeitSchliessen;
	plcbit KlappeIstOffenOut;
	plcbit KlappeIstGeschlOut;
	plcbit stateEntry;
};
_BUR_PUBLIC void fbBoxenKlappenanst(struct fbBoxenKlappenanst* inst);
struct fbBoxenVentKlappen
{	float DrzVent1UmschMitLuftaufb;
	float DrzVent2UmschMitLuftaufb;
	float DrehzahlVent1Umsch;
	float DrehzahlVent2Umsch;
	float DrehzahlVent1Betrieb;
	float DrehzahlVent2Betrieb;
	float DrehzahlVent1Min;
	float DrehzahlVent1Max;
	float DrehzahlVent2Min;
	float DrehzahlVent2Max;
	float RampeVent1Up;
	float RampeVent1Down;
	float RampeVent2Up;
	float RampeVent2Down;
	unsigned long LaufzeitBypassklappe;
	unsigned long LaufzeitUmschaltklappe1;
	unsigned long LaufzeitUmschaltklappe2;
	unsigned long LaufzeitBoxenklappe1;
	unsigned long LaufzeitBoxenklappe2;
	unsigned long LaufzeitBoxenklappe3;
	unsigned long LaufzeitBoxenklappe4;
	unsigned long LaufzeitBoxenklappe5;
	unsigned long LaufzeitBoxenklappe6;
	unsigned long AnlaufverzZweiterVent;
	float DrehzahlVent1Out;
	float DrehzahlVent2Out;
	unsigned char curStep;
	unsigned long RestAnlaufverzoegerung;
	struct fbLascoEUhr fbLascoEUhr_0;
	struct fbLascoZdxx fbLascoZdxx_0;
	struct fbLascoFU fbFuVentilator1;
	struct fbLascoFU fbFuVentilator2;
	struct fbBoxenKlappenanst Bypassklappe;
	struct fbBoxenKlappenanst Umschaltklappe1;
	struct fbBoxenKlappenanst Umschaltklappe2;
	struct fbBoxenKlappenanst Boxenklappe1;
	struct fbBoxenKlappenanst Boxenklappe2;
	struct fbBoxenKlappenanst Boxenklappe3;
	struct fbBoxenKlappenanst Boxenklappe4;
	struct fbBoxenKlappenanst Boxenklappe5;
	struct fbBoxenKlappenanst Boxenklappe6;
	unsigned char nextStep;
	unsigned char lastStep;
	struct TON TON_AnlaufverzVentilatoren;
	plcbit Freigabe;
	plcbit Ventilator1InBetrieb;
	plcbit Ventilator2InBetrieb;
	plcbit AnforderungVentilator1;
	plcbit AnforderungVentilator2;
	plcbit LuftaufbereitungInBetrieb;
	plcbit BypassklappeOeffnen;
	plcbit BypassklappeSchliessen;
	plcbit Umschaltkl1Oeffnen;
	plcbit Umschaltkl1Schliessen;
	plcbit Umschaltkl2Oeffnen;
	plcbit Umschaltkl2Schliessen;
	plcbit Boxenklappe1Oeffnen;
	plcbit Boxenklappe1Schliessen;
	plcbit Boxenklappe2Oeffnen;
	plcbit Boxenklappe2Schliessen;
	plcbit Boxenklappe3Oeffnen;
	plcbit Boxenklappe3Schliessen;
	plcbit Boxenklappe4Oeffnen;
	plcbit Boxenklappe4Schliessen;
	plcbit Boxenklappe5Oeffnen;
	plcbit Boxenklappe5Schliessen;
	plcbit Boxenklappe6Oeffnen;
	plcbit Boxenklappe6Schliessen;
	plcbit EndlBypassGeschl;
	plcbit EndlBypassOffen;
	plcbit EndlUmschaltkl1Geschl;
	plcbit EndlUmschaltkl1Offen;
	plcbit EndlUmschaltkl2Geschl;
	plcbit EndlUmschaltkl2Offen;
	plcbit EndlBoxenklappe1Offen;
	plcbit EndlBoxenklappe1Geschl;
	plcbit EndlBoxenklappe2Offen;
	plcbit EndlBoxenklappe2Geschl;
	plcbit EndlBoxenklappe3Offen;
	plcbit EndlBoxenklappe3Geschl;
	plcbit EndlBoxenklappe4Offen;
	plcbit EndlBoxenklappe4Geschl;
	plcbit EndlBoxenklappe5Offen;
	plcbit EndlBoxenklappe5Geschl;
	plcbit EndlBoxenklappe6Offen;
	plcbit EndlBoxenklappe6Geschl;
	plcbit QuitFehler;
	plcbit Boxenklappe6Vorhanden;
	plcbit Boxenklappe5Vorhanden;
	plcbit Boxenklappe4Vorhanden;
	plcbit Boxenklappe3Vorhanden;
	plcbit Boxenklappe2Vorhanden;
	plcbit Boxenklappe1Vorhanden;
	plcbit UmluftklVonVent1Abhaengig;
	plcbit UmluftklVonVent2Abhaengig;
	plcbit Boxenkl1VonVent1Abhaengig;
	plcbit Boxenkl1VonVent2Abhaengig;
	plcbit Boxenkl2VonVent1Abhaengig;
	plcbit Boxenkl2VonVent2Abhaengig;
	plcbit Boxenkl3VonVent1Abhaengig;
	plcbit Boxenkl3VonVent2Abhaengig;
	plcbit Boxenkl4VonVent1Abhaengig;
	plcbit Boxenkl4VonVent2Abhaengig;
	plcbit Boxenkl5VonVent1Abhaengig;
	plcbit Boxenkl5VonVent2Abhaengig;
	plcbit Boxenkl6VonVent1Abhaengig;
	plcbit Boxenkl6VonVent2Abhaengig;
	plcbit BypassklVonVent1Abhaengig;
	plcbit BypassklVonVent2Abhaengig;
	plcbit EndlagenVhdBoxenklappe1;
	plcbit EndlagenVhdBoxenklappe2;
	plcbit EndlagenVhdBoxenklappe3;
	plcbit EndlagenVhdBoxenklappe4;
	plcbit EndlagenVhdBoxenklappe5;
	plcbit EndlagenVhdBoxenklappe6;
	plcbit EndlagenVhdUmschaltklappe1;
	plcbit EndlagenVhdUmschaltklappe2;
	plcbit EndlagenVhdBypassklappe;
	plcbit FreigabeVentilator1Out;
	plcbit FreigabeVentilator2Out;
	plcbit BypassSchliessenOut;
	plcbit BypassOeffnenOut;
	plcbit Umschaltkl1SchliessenOut;
	plcbit Umschaltkl1OeffnenOut;
	plcbit Umschaltkl2SchliessenOut;
	plcbit Umschaltkl2OeffnenOut;
	plcbit Boxenklappe1OeffnenOut;
	plcbit Boxenklappe1SchliessenOut;
	plcbit Boxenklappe2OeffnenOut;
	plcbit Boxenklappe2SchliessenOut;
	plcbit Boxenklappe3OeffnenOut;
	plcbit Boxenklappe3SchliessenOut;
	plcbit Boxenklappe4OeffnenOut;
	plcbit Boxenklappe4SchliessenOut;
	plcbit Boxenklappe5OeffnenOut;
	plcbit Boxenklappe5SchliessenOut;
	plcbit Boxenklappe6OeffnenOut;
	plcbit Boxenklappe6SchliessenOut;
	plcbit UmschaltungAktiv;
	plcbit FehlerLaufzeitBypass;
	plcbit FehlerLaufzeitUmschaltkl1;
	plcbit FehlerLaufzeitUmschaltkl2;
	plcbit FehlerLaufzeitKlappeBox1;
	plcbit FehlerLaufzeitKlappeBox2;
	plcbit FehlerLaufzeitKlappeBox3;
	plcbit FehlerLaufzeitKlappeBox4;
	plcbit FehlerLaufzeitKlappeBox5;
	plcbit FehlerLaufzeitKlappeBox6;
	plcbit FehlerFuVentilator1;
	plcbit BypassklappeIstGeschl;
	plcbit BypassklappeIstOffen;
	plcbit Umschaltklappe1IstGeschl;
	plcbit Umschaltklappe1IstOffen;
	plcbit Umschaltklappe2IstGeschl;
	plcbit Umschaltklappe2IstOffen;
	plcbit Boxenklappe1IstOffen;
	plcbit Boxenklappe1IstGeschl;
	plcbit Boxenklappe2IstOffen;
	plcbit Boxenklappe2IstGeschl;
	plcbit Boxenklappe3IstOffen;
	plcbit Boxenklappe3IstGeschl;
	plcbit Boxenklappe4IstOffen;
	plcbit Boxenklappe4IstGeschl;
	plcbit Boxenklappe5IstOffen;
	plcbit Boxenklappe5IstGeschl;
	plcbit Boxenklappe6IstOffen;
	plcbit Boxenklappe6IstGeschl;
	plcbit FehlerFuVentilator2;
	plcbit AnlaufverzVent1Aktiv;
	plcbit AnlaufverzVent2Aktiv;
	plcbit sekTick;
	plcbit loc_AenderungBypassklappe;
	plcbit loc_AenderungUmschaltklappe1;
	plcbit loc_AenderungUmschaltklappe2;
	plcbit loc_AenderungBoxenklappe1;
	plcbit loc_AenderungBoxenklappe2;
	plcbit loc_AenderungBoxenklappe3;
	plcbit loc_AenderungBoxenklappe4;
	plcbit loc_AenderungBoxenklappe5;
	plcbit loc_AenderungBoxenklappe6;
	plcbit loc_UmschaltungErforderlVent1;
	plcbit loc_UmschaltungErforderlVent2;
	plcbit stateEntry;
};
_BUR_PUBLIC void fbBoxenVentKlappen(struct fbBoxenVentKlappen* inst);
