#ifndef __AS__TYPE_
#define __AS__TYPE_
typedef struct {
	unsigned char bit0  : 1;
	unsigned char bit1  : 1;
	unsigned char bit2  : 1;
	unsigned char bit3  : 1;
	unsigned char bit4  : 1;
	unsigned char bit5  : 1;
	unsigned char bit6  : 1;
	unsigned char bit7  : 1;
} _1byte_bit_field_;

typedef struct {
	unsigned short bit0  : 1;
	unsigned short bit1  : 1;
	unsigned short bit2  : 1;
	unsigned short bit3  : 1;
	unsigned short bit4  : 1;
	unsigned short bit5  : 1;
	unsigned short bit6  : 1;
	unsigned short bit7  : 1;
	unsigned short bit8  : 1;
	unsigned short bit9  : 1;
	unsigned short bit10 : 1;
	unsigned short bit11 : 1;
	unsigned short bit12 : 1;
	unsigned short bit13 : 1;
	unsigned short bit14 : 1;
	unsigned short bit15 : 1;
} _2byte_bit_field_;

typedef struct {
	unsigned long bit0  : 1;
	unsigned long bit1  : 1;
	unsigned long bit2  : 1;
	unsigned long bit3  : 1;
	unsigned long bit4  : 1;
	unsigned long bit5  : 1;
	unsigned long bit6  : 1;
	unsigned long bit7  : 1;
	unsigned long bit8  : 1;
	unsigned long bit9  : 1;
	unsigned long bit10 : 1;
	unsigned long bit11 : 1;
	unsigned long bit12 : 1;
	unsigned long bit13 : 1;
	unsigned long bit14 : 1;
	unsigned long bit15 : 1;
	unsigned long bit16 : 1;
	unsigned long bit17 : 1;
	unsigned long bit18 : 1;
	unsigned long bit19 : 1;
	unsigned long bit20 : 1;
	unsigned long bit21 : 1;
	unsigned long bit22 : 1;
	unsigned long bit23 : 1;
	unsigned long bit24 : 1;
	unsigned long bit25 : 1;
	unsigned long bit26 : 1;
	unsigned long bit27 : 1;
	unsigned long bit28 : 1;
	unsigned long bit29 : 1;
	unsigned long bit30 : 1;
	unsigned long bit31 : 1;
} _4byte_bit_field_;
#endif

#ifndef __AS__TYPE_Zeit_type
#define __AS__TYPE_Zeit_type
typedef struct Zeit_type
{	unsigned short Jahr;
	unsigned char Monat;
	unsigned char Tag;
	unsigned char WoTag;
	unsigned char Stunde;
	unsigned char Minute;
	unsigned char Sekunde;
	unsigned short Milli;
	unsigned short Mikro;
} Zeit_type;
#endif

struct DTGetTime
{	unsigned short status;
	plcdt DT1;
	plcbit enable;
};
_BUR_PUBLIC void DTGetTime(struct DTGetTime* inst);
struct TON
{	plctime PT;
	plctime ET;
	plctime StartTime;
	unsigned long Restart;
	plcbit IN;
	plcbit Q;
	plcbit M;
};
_BUR_PUBLIC void TON(struct TON* inst);
struct fbLascoEUhr
{	signed short StdMin;
	unsigned short Jahr;
	unsigned char Monat;
	unsigned char Tag;
	unsigned char WoTag;
	unsigned char Stunde;
	unsigned char Minute;
	unsigned char Sekunde;
	unsigned short Milli;
	unsigned short Mikro;
	Zeit_type Echtzeit;
	struct DTGetTime DTGetTime_0;
	plcdt DateTime;
	plcbit Freigabe;
};
_BUR_PUBLIC void fbLascoEUhr(struct fbLascoEUhr* inst);
struct fbLascoTON
{	float Zeit;
	float Elapsed;
	plcbit IN;
	plcbit Tick;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoTON(struct fbLascoTON* inst);
struct fbLascoZdxx
{	float IN;
	float MEM;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoZdxx(struct fbLascoZdxx* inst);
struct SysInfo
{	unsigned char init_reason;
	unsigned char init_count;
	unsigned long tick_count;
	unsigned long version;
	plcbit enable;
};
_BUR_PUBLIC void SysInfo(struct SysInfo* inst);
struct LCRRamp
{	float x;
	float dy_up;
	float dy_down;
	float y_max;
	float y_min;
	float y_set;
	unsigned short status;
	float y;
	signed long y_dbl_1;
	signed long y_dbl_2;
	unsigned long timestore1;
	unsigned long timestore2;
	unsigned long getDtForceOff;
	struct SysInfo sysinfo_inst;
	plcbit enable;
	plcbit set;
	plcbit x_reached;
	plcbit max_limit;
	plcbit min_limit;
};
_BUR_PUBLIC void LCRRamp(struct LCRRamp* inst);
struct fbLascoFU
{	float SollDrehzahl;
	float AnsprechZeitFU;
	float RampeUpSek;
	float RampeDownSek;
	float MaxDrehzahl;
	float MinDrehzahl;
	float DrehzahlFU;
	struct fbLascoTON TON_Betriebsmeldung;
	struct LCRRamp LCRRamp_0;
	signed long RampDownMillis;
	signed long RampUpMillis;
	float IstDrehzahl;
	plcbit Freigabe;
	plcbit BetrMldg;
	plcbit Reset;
	plcbit Tick;
	plcbit BetriebFU;
	plcbit StoerungFU;
	plcbit zzEdge00000;
	plcbit zzEdge00001;
	plcbit zzEdge00002;
	plcbit InitDone;
	plcbit ResetDone;
	plcbit Init;
	plcbit zzEdge00003;
};
_BUR_PUBLIC void fbLascoFU(struct fbLascoFU* inst);
struct fbEntfKompressor
{	float EintrittFeuchte;
	float parFeuchteEin;
	float parFeuchteAus;
	unsigned long parEinschaltverzAbtau;
	unsigned long parAusschaltverzAbtau;
	unsigned long parEinschaltverzKompressor;
	float Hochdruck;
	float Niederdruck;
	float parNiederdruckMin;
	float parHochdruckMax;
	float parNiederdruckMax;
	float DrehzahlvorgabeFU;
	float DrehzahlMin;
	float DrehzahlMax;
	float RampeUp;
	float RampeDown;
	unsigned long parEinschaltverzMagnetventil;
	float parNiederdruckPumpdown;
	unsigned long parVerzStandbyBeiKlappenumsch;
	float DrehzahlOut;
	unsigned char curStep;
	struct TON TON_Abtau;
	struct TON TON_Kompressor;
	unsigned char lastStep;
	unsigned char nextStep;
	struct fbLascoFU fbFuKompressor;
	struct fbLascoEUhr fbLascoEUhr_0;
	struct fbLascoZdxx fbLascoZdxx_0;
	struct TON TON_EinschaltverzMagnetventil;
	struct TON TON_LaufzeitPumpdown;
	struct TON TON_Klappenumschaltung;
	plcbit SicherheitOk;
	plcbit Freigabe;
	plcbit BetriebsmldgVentilator;
	plcbit Automatik;
	plcbit Dauerbetrieb;
	plcbit StatusSensorNiederdruckOk;
	plcbit StatusSensorEintrittOk;
	plcbit BetriebsmldgKompressor;
	plcbit QuitFehler;
	plcbit diNiederdruckOk;
	plcbit diHochdruckOk;
	plcbit KlappenumschaltungAkiv;
	plcbit FreigabeKompressorOut;
	plcbit StoerungOut;
	plcbit AbtauungAktiv;
	plcbit MagnetventilOut;
	plcbit loc_StatusFeuchteOk;
	plcbit FehlerPumpdown;
	plcbit StandbyKlappenumsch;
	plcbit stateEntry;
	plcbit sekTick;
};
_BUR_PUBLIC void fbEntfKompressor(struct fbEntfKompressor* inst);
