struct fbLascoZdxx
{	float IN;
	float MEM;
	plcbit Q;
};
_BUR_PUBLIC void fbLascoZdxx(struct fbLascoZdxx* inst);
struct fbLascoPuge
{	float ZeitPuls;
	float ZeitPause;
	float RestzeitPuls;
	float RestzeitPause;
	unsigned char currStep;
	float CounterPuls;
	float CounterPause;
	unsigned char nextStep;
	plcbit StartMitPuls;
	plcbit StartMitPause;
	plcbit Tick;
	plcbit Reset;
	plcbit PulsQ;
	plcbit PauseQ;
};
_BUR_PUBLIC void fbLascoPuge(struct fbLascoPuge* inst);
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_0;
_BUR_LOCAL plcbit hmilliTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_1;
_BUR_LOCAL plcbit sekTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_2;
_BUR_LOCAL plcbit stdTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_3;
_BUR_LOCAL plcbit tagTick;
_BUR_LOCAL struct fbLascoZdxx fbLascoZdxx_5;
_BUR_LOCAL plcbit jahrTick;
_BUR_LOCAL struct fbLascoPuge fbLascoPuge_0;
_BUR_LOCAL plcbit hmiBlink;
_BUR_LOCAL struct fbLascoPuge fbLascoPuge_1;
_BUR_LOCAL plcbit hmiBlink2;
_BUR_LOCAL plcbit loc_Box1Beendet;
_BUR_LOCAL plcbit loc_Box2Beendet;
_BUR_LOCAL plcbit loc_Box6Beendet;
_BUR_LOCAL plcbit loc_Box5Beendet;
_BUR_LOCAL plcbit loc_Box4Beendet;
_BUR_LOCAL plcbit loc_Box3Beendet;
_BUR_LOCAL unsigned char warmluft1_button_color;
_BUR_LOCAL unsigned char warmluft2_button_color;
