#ifndef __AS__TYPE_
#define __AS__TYPE_
typedef struct {
	unsigned char bit0  : 1;
	unsigned char bit1  : 1;
	unsigned char bit2  : 1;
	unsigned char bit3  : 1;
	unsigned char bit4  : 1;
	unsigned char bit5  : 1;
	unsigned char bit6  : 1;
	unsigned char bit7  : 1;
} _1byte_bit_field_;

typedef struct {
	unsigned short bit0  : 1;
	unsigned short bit1  : 1;
	unsigned short bit2  : 1;
	unsigned short bit3  : 1;
	unsigned short bit4  : 1;
	unsigned short bit5  : 1;
	unsigned short bit6  : 1;
	unsigned short bit7  : 1;
	unsigned short bit8  : 1;
	unsigned short bit9  : 1;
	unsigned short bit10 : 1;
	unsigned short bit11 : 1;
	unsigned short bit12 : 1;
	unsigned short bit13 : 1;
	unsigned short bit14 : 1;
	unsigned short bit15 : 1;
} _2byte_bit_field_;

typedef struct {
	unsigned long bit0  : 1;
	unsigned long bit1  : 1;
	unsigned long bit2  : 1;
	unsigned long bit3  : 1;
	unsigned long bit4  : 1;
	unsigned long bit5  : 1;
	unsigned long bit6  : 1;
	unsigned long bit7  : 1;
	unsigned long bit8  : 1;
	unsigned long bit9  : 1;
	unsigned long bit10 : 1;
	unsigned long bit11 : 1;
	unsigned long bit12 : 1;
	unsigned long bit13 : 1;
	unsigned long bit14 : 1;
	unsigned long bit15 : 1;
	unsigned long bit16 : 1;
	unsigned long bit17 : 1;
	unsigned long bit18 : 1;
	unsigned long bit19 : 1;
	unsigned long bit20 : 1;
	unsigned long bit21 : 1;
	unsigned long bit22 : 1;
	unsigned long bit23 : 1;
	unsigned long bit24 : 1;
	unsigned long bit25 : 1;
	unsigned long bit26 : 1;
	unsigned long bit27 : 1;
	unsigned long bit28 : 1;
	unsigned long bit29 : 1;
	unsigned long bit30 : 1;
	unsigned long bit31 : 1;
} _4byte_bit_field_;
#endif

struct fbTrockTarifabsch
{	float StartMin1;
	float StartStd1;
	float StartMin2;
	float StartStd2;
	float StartMin3;
	float StartStd3;
	float AktZeit;
	float StoppMin1;
	float StoppStd1;
	float StoppMin2;
	float StoppStd2;
	float StoppMin3;
	float StoppStd3;
	float VorlaufzeitLuftaufbMin;
	float StartZeit2;
	float StartZeit3;
	float StartZeit1;
	float StoppZeit2;
	float StoppZeit3;
	float StoppZeit1;
	float loc_StdVorlaufzeitREAL;
	signed short loc_StdVorlaufzeit;
	float loc_MinVorlaufzeit;
	float loc_ZwischenergStartStd;
	float loc_StartStdLuftaufb;
	float loc_ZwischenergStartMin;
	float loc_StartMinLuftaufb;
	float StartZeitLuftaufb1;
	float StartZeitLuftaufb2;
	float StartZeitLuftaufb3;
	plcbit Freigabe;
	plcbit TarifabschaltungLuftaufbEin;
	plcbit TarifabschaltungEin;
	plcbit FreigZeitfenster1;
	plcbit FreigZeitfenster2;
	plcbit FreigZeitfenster3;
	plcbit FreigabeZeitfensterLuftaufb1;
	plcbit FreigabeZeitfensterLuftaufb2;
	plcbit FreigabeZeitfensterLuftaufb3;
};
_BUR_PUBLIC void fbTrockTarifabsch(struct fbTrockTarifabsch* inst);
_BUR_PUBLIC float CheckDivReal(float divisor);
