
TYPE
	CSV_typ : 	STRUCT 
		IW : CSV_IW_typ;
		SW : CSV_SW_typ;
		FE : CSV_FE_typ;
		WA : CSV_WA_typ;
	END_STRUCT;
	CSV_IW_typ : 	STRUCT 
		RPS_SAVE_STEP_Nr : UINT;
		RPS_CPYDEL_STEP_Nr : UINT;
		RPS_SAVE_STEP_Text : STRING[80];
		RPS_CPYDEL_STEP_Text : STRING[80];
		SFehler : BOOL;
		SFehler_Nr : USINT;
		SWarnung : BOOL;
		SWarnung_Nr : USINT;
		KOPF_WRITE : BOOL;
		DATA_WRITE : BOOL;
		DATA_WRITE_BEREIT : BOOL;
		Zyklus_t_akt : UDINT;
		Zyklus_t_letzt : UDINT;
		DatObj_Zeilen_Anz : UINT;
		DatObj_Tag_ID_ZeileNr : UINT;
		DatObj_Tag_Variable_ZeileNr : UINT;
		DatObj_Tag_Datentyp_ZeileNr : UINT;
		DatObj_Tag_MIN_ZeileNr : UINT;
		DatObj_Tag_MAX_ZeileNr : UINT;
		RPS_DirRead_Start_OK : BOOL;
		RPS_COPY_AUTO_Start : BOOL;
		DirRead_FileName_alt : STRING[260];
		DirRead_FileName_neu : STRING[260];
		PC_DevLink_Param : STRING[200];
		PC_Device : STRING[20];
		PC_Zielpfad : STRING[100];
		EXT_Device : STRING[20];
		EXT_Zielpfad : STRING[100];
		RPS_Device : ARRAY[0..19] OF USINT;
		RPS_Zielpfad : ARRAY[0..19] OF USINT;
		RPS_DirCreate_OK : BOOL;
		RPS_FileCreate_OK : BOOL;
		RPS_FileOpen_OK : BOOL;
		RPS_FileWrite_OK : BOOL;
		RPS_FileRead_OK : BOOL;
		RPS_FileClose_OK : BOOL;
		RPS_MemInfo_OK : BOOL;
		RPS_DirInfo_OK : BOOL;
		RPS_DirRead_OK : BOOL;
		RPS_FileDelete_OK : BOOL;
		RPS_DirDeleteEx_OK : BOOL;
		PC_DevLink_OK : BOOL;
		PC_DirCreate_OK : BOOL;
		PC_FileCopy_OK : BOOL;
		PC_DirCopy_OK : BOOL;
		EXT_DirCreate_OK : BOOL;
		EXT_FileCopy_OK : BOOL;
		EXT_DirCopy_OK : BOOL;
		RPS_DirCreate_FehlerNr : UINT;
		RPS_FileCreate_FehlerNr : UINT;
		RPS_FileOpen_FehlerNr : UINT;
		RPS_FileWrite_FehlerNr : UINT;
		RPS_FileRead_FehlerNr : UINT;
		RPS_FileClose_FehlerNr : UINT;
		RPS_MemInfo_FehlerNr : UINT;
		RPS_DirInfo_FehlerNr : UINT;
		RPS_DirRead_FehlerNr : UINT;
		RPS_FileDelete_FehlerNr : UINT;
		RPS_DirCopy_FehlerNr : UINT;
		RPS_DirDeleteEx_FehlerNr : UINT;
		PC_DevLink_FehlerNr : UINT;
		PC_DirCreate_FehlerNr : UINT;
		PC_FileCopy_FehlerNr : UINT;
		PC_DirCopy_FehlerNr : UINT;
		EXT_DirCreate_FehlerNr : UINT;
		EXT_FileCopy_FehlerNr : UINT;
		EXT_DirCopy_FehlerNr : UINT;
		RPS_DirCreate_OK_Z : UDINT;
		RPS_DirCreate_FEHLER_Z : UDINT;
		RPS_FileCreate_OK_Z : UDINT;
		RPS_FileCreate_FEHLER_Z : UDINT;
		RPS_FileOpen_OK_Z : UDINT;
		RPS_FileOpen_FEHLER_Z : UDINT;
		RPS_FileWrite_OK_Z : UDINT;
		RPS_FileWrite_FEHLER_Z : UDINT;
		RPS_FileRead_OK_Z : UDINT;
		RPS_FileRead_FEHLER_Z : UDINT;
		RPS_FileClose_OK_Z : UDINT;
		RPS_FileClose_FEHLER_Z : UDINT;
		RPS_MemInfo_OK_Z : UDINT;
		RPS_MemInfo_FEHLER_Z : UDINT;
		RPS_DirInfo_OK_Z : UDINT;
		RPS_DirInfo_FEHLER_Z : UDINT;
		RPS_DirRead_OK_Z : UDINT;
		RPS_DirRead_FEHLER_Z : UDINT;
		RPS_FileDelete_OK_Z : UDINT;
		RPS_FileDelete_FEHLER_Z : UDINT;
		RPS_DirDeleteEx_OK_Z : UDINT;
		RPS_DirDeleteEx_FEHLER_Z : UDINT;
		PC_DevLink_OK_Z : UDINT;
		PC_DevLink_FEHLER_Z : UDINT;
		PC_DirCreate_OK_Z : UDINT;
		PC_DirCreate_FEHLER_Z : UDINT;
		PC_FileCopy_OK_Z : UDINT;
		PC_FileCopy_FEHLER_Z : UDINT;
		PC_DirCopy_OK_Z : UDINT;
		PC_DirCopy_FEHLER_Z : UDINT;
		EXT_DirCreate_OK_Z : UDINT;
		EXT_DirCreate_FEHLER_Z : UDINT;
		EXT_FileCopy_OK_Z : UDINT;
		EXT_FileCopy_FEHLER_Z : UDINT;
		EXT_DirCopy_OK_Z : UDINT;
		EXT_DirCopy_FEHLER_Z : UDINT;
		Version : ARRAY[0..19] OF USINT;
		Anlagename : ARRAY[0..19] OF USINT;
		File_Name : STRING[100];
		RPS_File_Name : STRING[200];
		RPS_Mem_frei : UDINT;
		RPS_Mem_frei_prz : REAL;
		RPS_Mem_gesamt : UDINT;
		RPS_DirInfo_FileNum : UDINT;
		RPS_DirInfo_DirNum : UDINT;
		RPS_DirRead_Data : fiDIR_READ_DATA;
		Kopf_length : UDINT;
		Datensatz_length : UDINT;
		Datensatz_TimeStamp : ARRAY[0..24] OF USINT;
	END_STRUCT;
	CSV_SW_typ : 	STRUCT 
		SPERRE_T : BOOL;
		KOPF_WRITE_T : BOOL;
		DATA_WRITE_T : BOOL;
		F_Quitt_T : BOOL;
		Gruebl_Reporting_T : BOOL;
		QM_HeizW_T : BOOL;
		QM_HeizW_BetrJahr_Mon : USINT;
		Kopf_Version_T : BOOL;
		Kopf_Anlagenname_T : BOOL;
		Kopf_ID_T : BOOL;
		Kopf_Bezeichnung_T : BOOL;
		Kopf_Einheit_T : BOOL;
		Kopf_Datentyp_T : BOOL;
		Kopf_MIN_MAX_T : BOOL;
		Zeitstempel_lang_T : BOOL;
		Begrenzung_MINMAX_T : BOOL;
		RPS_Mem_frei_przN : REAL;
		RPS_COPY_AUTO_T : BOOL;
		RPS_MEMORY_AUTO_T : BOOL;
		RPS_FileDelete_alt_HAND_T : BOOL;
		RPS_FileDelete_neu_HAND_T : BOOL;
		RPS_DirDeleteEx_HAND_T : BOOL;
		PC_FileCopy_alt_HAND_T : BOOL;
		PC_FileCopy_neu_HAND_T : BOOL;
		PC_DirCopy_HAND_T : BOOL;
		EXT_FileCopy_alt_HAND_T : BOOL;
		EXT_FileCopy_neu_HAND_T : BOOL;
		EXT_DirCopy_HAND_T : BOOL;
	END_STRUCT;
	CSV_FE_typ : 	STRUCT 
		Datensatz_Fehler : BOOL;
		DatObj_CFG : BOOL;
		DatObj_CFG_length : BOOL;
		DatObj_Tag_ID : BOOL;
		DatObj_Tag_Variable : BOOL;
		DatObj_Tag_Datentyp : BOOL;
		DatObj_Tag_MIN : BOOL;
		DatObj_Tag_MAX : BOOL;
		DatObj_ZeilenMAX : BOOL;
		RPS_kein_Speicherplatz : BOOL;
		RPS_DirCreate : BOOL;
		RPS_FileCreate : BOOL;
		RPS_FileOpen : BOOL;
		RPS_FileClose : BOOL;
		RPS_FileWrite : BOOL;
		RPS_FileRead : BOOL;
		RPS_MemInfo : BOOL;
		RPS_DirInfo : BOOL;
		RPS_DirRead : BOOL;
		RPS_FileDelete : BOOL;
		RPS_DirDeleteEx : BOOL;
		PC_DevLink : BOOL;
		PC_DirCreate : BOOL;
		PC_FileCopy : BOOL;
		PC_DirCopy : BOOL;
		EXT_DirCreate : BOOL;
		EXT_FileCopy : BOOL;
		EXT_DirCopy : BOOL;
	END_STRUCT;
	CSV_WA_typ : 	STRUCT 
		RPS_Datei_alt_geloescht : BOOL;
		File_not_found : BOOL;
	END_STRUCT;
	CSV_DatObj1_typ : 	STRUCT 
		Version : ARRAY[0..19] OF USINT;
		Anlagename : ARRAY[0..19] OF USINT;
		RPS_Device : ARRAY[0..19] OF USINT;
		RPS_Zielpfad : ARRAY[0..19] OF USINT;
		EXT_Device : ARRAY[0..19] OF USINT;
		EXT_Zielpfad : ARRAY[0..19] OF USINT;
		PC_IP_Adresse : ARRAY[0..19] OF USINT;
		PC_Ordnerfreigabe : ARRAY[0..19] OF USINT;
		PC_Username : ARRAY[0..19] OF USINT;
		PC_Userpassword : ARRAY[0..19] OF USINT;
		PC_Zielpfad : ARRAY[0..99] OF USINT;
	END_STRUCT;
	CSV_DatObj2_typ : 	STRUCT 
		Tag_ID : DINT;
		Tag_Variablenname : ARRAY[0..47] OF USINT;
		Tag_Bezeichnung : ARRAY[0..59] OF USINT;
		Tag_Einheit : ARRAY[0..31] OF USINT;
		Tag_MIN : ARRAY[0..15] OF USINT;
		Tag_MAX : ARRAY[0..15] OF USINT;
	END_STRUCT;
END_TYPE
